# -*- coding: utf-8 -*-
"""TA_doc_parsing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GW5pITW4GxK7LQpkU_fg45-wqKFnTpJx

# Import libraries
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install google-cloud-documentai -q

import os
from typing import Optional
from google.cloud import documentai
from google.api_core.client_options import ClientOptions
from google.colab import auth # Added for authentication
# Authenticate to Google Cloud
auth.authenticate_user()

"""# Define parameters"""

project_id = "wealth-report"
location = "eu" # Format is "us" or "eu"
processor_id = "70b690b94894b43" # Create processor before running sample
mime_type = "application/pdf" # Refer to https://cloud.google.com/document-ai/docs/file-types for supported file types
field_mask = "text,entities,fund name, amount"  # Optional. The fields to return in the Document object.

"""# Functions"""

def process_document_sample(
    project_id: str,
    location: str,
    processor_id: str,
    file_path: str,
    mime_type: str,
    field_mask: Optional[str] = None,
    processor_version_id: Optional[str] = None,
) -> None:
    # You must set the `api_endpoint` if you use a location other than "us".
    opts = ClientOptions(api_endpoint=f"{location}-documentai.googleapis.com")

    client = documentai.DocumentProcessorServiceClient(client_options=opts)

    if processor_version_id:
        # The full resource name of the processor version, e.g:
        # `projects/{project_id}/locations/{location}/processors/{processor_id}/processorVersions/{processor_version_id}`
        name = client.processor_version_path(
            project_id, location, processor_id, processor_version_id
        )
    else:
        # The full resource name of the processor, e.g.:
        # `projects/{project_id}/locations/{location}/processors/{processor_id}`
        name = client.processor_path(project_id, location, processor_id)

    # Read the file into memory
    with open(file_path, "rb") as image:
        image_content = image.read()

    # Load binary data
    raw_document = documentai.RawDocument(content=image_content, mime_type=mime_type)

    # For more information: https://cloud.google.com/document-ai/docs/reference/rest/v1/ProcessOptions
    # Optional: Additional configurations for processing.
    process_options = documentai.ProcessOptions(
        # Process only specific pages
        individual_page_selector=documentai.ProcessOptions.IndividualPageSelector(
            pages=[1]
        )
    )

    # Configure the process request
    request = documentai.ProcessRequest(
        name=name,
        raw_document=raw_document,
        field_mask=field_mask,
        process_options=process_options,
    )

    result = client.process_document(request=request)

    # For a full list of `Document` object attributes, reference this page:
    # https://cloud.cloud.google.com/document-ai/docs/reference/rest/v1/Document
    document = result.document

    # Read the text recognition output from the processor
    # print("The document contains the following text:")
    # print(document.text)
    return result


# [END documentai_process_document]

# Call the function to process the document
# result = process_document_sample(project_id, location, processor_id, file_path, mime_type, field_mask)

import json

def normalize_lines(raw: str):
    return [l.strip() for l in raw.split("\n") if l.strip()]

def detect_format(lines):
    text = " ".join(lines)
    if "DAILY SUBSCRIPTION / REDEMPTION BOOKING SUMMARY" in text:
        return "TA"
    if "Daily Subscription Booking Summary" in text:
        return "HSBC"
    # extend with more heuristics if needed
    return "UNKNOWN"

def parse_ta(lines):
    # sender: first line (or use last legal-entity line if you prefer)
    sender = lines[0]

    # booking date: line after 'Booking Date'
    booking_date = None
    for i, l in enumerate(lines):
        if l.lower() == "booking date" and i + 1 < len(lines):
            booking_date = lines[i + 1]
            break

    # transaction type: look for 'Redemption' / 'Subscription' before table
    transaction_type = None
    for l in lines:
        if l.lower() in ("redemption", "subscription"):
            transaction_type = l.capitalize()
            break

    # transactions: serial no + fund name + units + amount
    transactions = []
    i = 0
    while i < len(lines):
        if lines[i].isdigit():
            no = int(lines[i])
            fund_name = lines[i+1]
            units = lines[i+2]
            amount = lines[i+3]
            transactions.append({
                "no": no,
                "fund_name": fund_name,
                "units": units,
                "amount": amount
            })
            i += 4
        else:
            i += 1

    # totals
    total_by_fund_units = total_by_fund_amount = None
    grand_total_units = grand_total_amount = None
    for i, l in enumerate(lines):
        if l.lower() == "total by fund" and i + 2 < len(lines):
            total_by_fund_units = lines[i+1]
            total_by_fund_amount = lines[i+2]
        if l.lower() == "grand total" and i + 2 < len(lines):
            grand_total_units = lines[i+1]
            grand_total_amount = lines[i+2]

    return {
        "sender": sender,
        "booking_date": booking_date,
        "transaction_type": transaction_type,
        "transactions": transactions,
        "totals": {
            "total_by_fund_units": total_by_fund_units,
            "total_by_fund_amount": total_by_fund_amount,
            "grand_total_units": grand_total_units,
            "grand_total_amount": grand_total_amount
        }
    }

def parse_hsbc(lines):
    # sender: FROM line
    sender = None
    for i, l in enumerate(lines):
        if l.upper() == "FROM":
            j = i + 1
            while j < len(lines) and lines[j] == ":":
                j += 1
            sender = lines[j] if j < len(lines) else None
            break

    # booking date: BOOK DATE
    booking_date = None
    for i, l in enumerate(lines):
        if l.upper() == "BOOK DATE":
            j = i + 1
            while j < len(lines) and lines[j] == ":":
                j += 1
            booking_date = lines[j] if j < len(lines) else None
            break

    # transaction type: from “… Booking Summary”
    transaction_type = None
    for l in lines:
        if "Booking Summary" in l:
            if "Subscription" in l:
                transaction_type = "Subscription"
            elif "Redemption" in l:
                transaction_type = "Redemption"
            break

    # funds: each fund name + SUB TOTAL block
    funds = []
    i = 0
    while i < len(lines):
        # heuristic: fund lines contain 'Fund' (case-insensitive) and are not headers
        if (
            "fund" in lines[i].lower()
            and lines[i] not in ("FUND NAME", "SUB TOTAL", "GRAND TOTAL")
            and "Booking Summary" not in lines[i]
        ):
            # collect 1–2 lines of name (handles broken lines like 'Maybank AsiaPac' + 'ex-Japan…')
            name_lines = [lines[i]]
            if (
                i + 1 < len(lines)
                and "MYR" not in lines[i+1]
                and "SUB TOTAL" not in lines[i+1]
                and "Page" not in lines[i+1]
            ):
                name_lines.append(lines[i+1])
                i += 1
            fund_name = " ".join(name_lines)

            # find SUB TOTAL for this fund
            j = i + 1
            sub_total = None
            while j < len(lines):
                if lines[j] == "SUB TOTAL":
                    if j + 1 < len(lines):
                        sub_total = lines[j+1]
                    i = j
                    break
                if lines[j] == "GRAND TOTAL":
                    break
                j += 1

            if sub_total is not None:
                funds.append({
                    "fund_name": fund_name,
                    "amount": sub_total
                })
        i += 1

    # grand total
    grand_total_amount = None
    for i, l in enumerate(lines):
        if l == "GRAND TOTAL" and i + 1 < len(lines):
            grand_total_amount = lines[i+1]
            break

    return {
        "sender": sender,
        "booking_date": booking_date,
        "transaction_type": transaction_type,
        "transactions": funds,   # same key name as TA for downstream code
        "totals": {
            "grand_total_amount": grand_total_amount
        }
    }

def parse_document(raw: str):
    lines = normalize_lines(raw)
    fmt = detect_format(lines)
    if fmt == "TA":
        data = parse_ta(lines)
    elif fmt == "HSBC":
        data = parse_hsbc(lines)
    else:
        raise ValueError("Unknown document format")
    return data

# Example usage:
# result = parse_document(raw)
# print(json.dumps(result, indent=2))

"""#Execute code"""

file_list = os.listdir(folder_path)
for file_name in file_list:
  file_path = os.path.join(folder_path, file_name)
  result = process_document_sample(project_id, location, processor_id, file_path, mime_type, field_mask)
  raw = result.document.text
  result = parse_document(raw)
  print(json.dumps(result, indent=2))